name: Docker | python:3.11-rc-alpine3.15

on:
  push:
    branches:
      - master

env:
  CONTEXT: python/3.11-rc/alpine3.15
  FILE_PATH: python/3.11-rc/alpine3.15
  REPO_NAME: lvillis/python

jobs:
  job:
    if: "contains(github.event.head_commit.message, 'build.all') || contains(github.event.head_commit.message, 'build.python') || contains(github.event.head_commit.message, 'build.python3.11-rc-alpine3.15')"
    env:
      TAG_NAME: 3.11-rc-alpine3.15
    name: latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.4.1

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.FILE_PATH }}/${{ env.TAG_NAME }}.Dockerfile
          push: true
          tags: ${{ env.REPO_NAME }}:${{ env.TAG_NAME }}
          cache-from: type=registry,ref=${{ env.REPO_NAME }}:${{ env.TAG_NAME }}
          cache-to: type=inline